#!/usr/bin/python -u
# vim: set fileencoding=utf-8 :
#
# (C) 2011 Guido Guenther <agx@sigxcpu.org>
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

import os
import shutil
import sys
import puppethooks.checkers as checkers
import puppethooks.git as git

debug = True

def main():
    ret = 0
    zero = '0000000000000000000000000000000000000000'

    try:
        os.environ['GIT_DIR']
    except KeyError:
        print >>sys.stderr, "Don't run this script from the command line."
        sys.exit(1)

    rev = 'HEAD'
    if not git.verify_rev(rev):
        rev=zero

    for old_mode, new_mode, old_sha, new_sha, status, name in git.diff_cached(rev):
        if debug:
            print "Checking %s" % name
        try:
            checkers.check(name)
        except checkers.CheckFailed as details:
            print >>sys.stderr, "Syntax check of '%s' failed" % name
            if details:
                if details.args[2]:
                    print >>sys.stderr, details.args[2]
                print >>sys.stderr, details.args[0]
            ret = 1

    print "Checking files syntax done. %s" % ["", "Will deny commit due to errors."][ret]
    return ret

if __name__ == '__main__':
    sys.exit(main())

# vim:et:ts=4:sw=4:et:sts=4:ai:set list listchars=tab\:»·,trail\:·:
